{
  imports = [
    ./desktop.nix
    ./dev.nix
    ./docker.nix
    ./gaming.nix
    ./lsp.nix
    ./jupyter.nix
    ./netclient.nix
    ./tailscale.nix
    ./pipewire.nix
    ./ssh.nix
    ./ai.nix
    ./ios.nix
    ./pam.nix
    ./llm-tools.nix
    ./netdata.nix
    ./agenix.nix
    ./auto-cpufreq.nix
  ];
}
